### ISSUE TITLE
followRelationships method doesn't properly maps relations

### ISSUE THREAD

**Issue by maximgubar** [mrichar1/jsonapi-vuex#80]
I have an entity (Product) which has 2 relations (Manufacturer and Supplier)
Product to Manufacturer has ManyToMany relations and in JSON response is returned as array
Product to Supplier has ManyToOne relations and it is always an object.

After the followRelationships() method is executed I have wrongly mapped data.
The Manufacturer relation is mapped correctly, but for the Supplier it is an empty object.

Thanks in advance for your help

**Comment by mrichar1** [comment]
Hi - can you post the JSON response, and the restructured object that the action returns? This will help me to identify the exact issue. Thanks!

**Comment by maximgubar** [comment]
JSON Response:
```json
{
  "links": {
    "self": "/api/products/similar_products?magentoProductId=4&include=supplier"
  },
  "meta": {
    "totalItems": 65
  },
  "data": [
    {
      "id": "/api/products/12898",
      "type": "Product",
      "attributes": {
        "_id": 12898,
        "sku": "111111",
        "name": "Gin 47% Vol.",
        "alcohol": 47,
        "size": 50,
        "price": 99.99,
        "basePrice": 0,
        "currency": "",
        "baseCurrency": "",
        "isInStock": true,
        "isVermouth": false,
        "hasMatches": true,
        "updatedAt": "2019-06-25T07:28:37+00:00",
        "createdAt": "2018-04-09T15:57:04+00:00"
      },
      "relationships": {
        "supplier": {
          "data": {
            "type": "Supplier",
            "id": "/api/suppliers/102"
          }
        },
        "magentoProducts": {
          "data": [
            {
              "type": "MagentoProduct",
              "id": "/api/magento_products/4"
            },
            {
              "type": "MagentoProduct",
              "id": "/api/magento_products/307"
            }
          ]
        }
      }
    }
  ],
  "included": [
    {
      "id": "/api/suppliers/102",
      "type": "Supplier",
      "attributes": {
        "_id": 102,
        "code": "supp1",
        "name": "supp1",
        "createdAt": "2018-04-06T08:58:29+00:00",
        "isDomestic": false,
        "currency": "USD"
      }
    }
  ]
}
```

Restructured Object:
```json
{
  "_jv": {
    "id": "/api/products/12898",
    "type": "Product",
    "relationships": {
      "supplier": {
        "data": {
          "type": "Supplier",
          "id": "/api/suppliers/102"
        }
      },
      "magentoProducts": {
        "data": [
          {
            "type": "MagentoProduct",
            "id": "/api/magento_products/4"
          },
          {
            "type": "MagentoProduct",
            "id": "/api/magento_products/307"
          }
        ]
      }
    }
  },
  "_id": 12898,
  "sku": "111111",
  "name": "Gin 47% Vol.",
  "alcohol": 47,
  "size": 50,
  "price": 99.99,
  "basePrice": 0,
  "currency": "",
  "baseCurrency": "",
  "isInStock": true,
  "isVermouth": false,
  "hasMatches": true,
  "updatedAt": "2019-06-25T07:28:37+00:00",
  "createdAt": "2018-04-09T15:57:04+00:00",
  "supplier": {},
  "magentoProducts": {
    "/api/magento_products/4": {},
    "/api/magento_products/307": {}
  }
}
```

**Comment by mrichar1** [comment]
Thanks - can you also confirm which version of `jsonapi-vuex` you are using? this looks at first glance like an issue which was fixed in a recent release.

**Comment by maximgubar** [comment]
it was 2.0.0, just updated to 2.1.0 and issue is still there

**Comment by mrichar1** [comment]
Thanks for the extra info.

I suspect the issue is related to the `id` containing slashes.

The endpoint URL is either the `links:self` url, or failing that it is constructed as `type/id`. 

So the Suppliers relationship will merge `type: Supplier` and `id: /api/suppliers/102` to give a URL of `/Supplier/api/suppliers/102`. Looking at the self link of the original object, this is probably not correct.

Something which should probably be changed in this module is to url-escape all ids, so that they are always interpreted as strings - i.e. `%2Fapi%2Fsuppliers%2F102`. However this doesn't solve the issue of the constructed URL remaining incorrect.

If you are in control of the API I'd strongly recommend not using URL-like characters in the id. Otherwise you may need to make use of the ability to customise Endpoints as documented here: https://github.com/mrichar1/jsonapi-vuex#Endpoints


The endpoint URL being constructed for the item with the `type` `Product` and `id` `/api/products/12898`? The default approach for this module`/Product/api/products/12898`

**Comment by maximgubar** [comment]
@mrichar1 yep, make sense.
atm, I've started [conversation](https://github.com/api-platform/core/issues/2287) on the framework(that we use for API) issuetracker in order to find the truth :)

and thanks for your superfast support.
